### ISSUE TITLE
Wrong file ending

### ISSUE THREAD

**Issue by Dakraid** [FransBouma/OtisFX#2]
It looks like the shader files within the OtisFX folder have the wrong file ending. Instead of .fx it should be .h otherwise they aren't loaded into ReShade. Not sure if intentional or not.

**Comment by FransBouma** [comment]
This is intentional, as the new reshade shaders all use .fx. You can use this one: https://github.com/crosire/reshade-shaders, which is the official reshade shader library, and OtisFX has been merged with that recently. 

It's indeed unfortunate, as standalone it looks weird. As the shaders are now part of Reshade's official library, I'll keep this repository around for small shader work before I'll merge them with reshade library. 

It's good you bring it up though. I'll update the readme to show this info, as it's indeed unclear!

**Comment by Dakraid** [comment]
Ahh, I see. Thank you for clearing that up.
